//! Crystalline Lineage
//! @prompt 00_nucleo/prompts/rules/module.md
//! @prompt-hash PENDING
//! @layer L1
//! @updated 2026-03-22

pub mod alien_file;
pub mod dangling_contract;
pub mod external_type_in_contract;
pub mod forbidden_import;
pub mod impure_core;
pub mod infrastructure_error;
pub mod multi_prompt_header;
pub mod mutable_state_core;
pub mod nucleus_integrity;
pub mod orphan_prompt;
pub mod prompt_drift;
pub mod prompt_header;
pub mod prompt_stale;
pub mod pub_leak;
pub mod quarantine_leak;
pub mod test_file;
pub mod wiring_logic_leak;
pub mod wildcard_saturation;
pub mod compound_guard;
pub mod range_pattern;
pub mod or_pattern_alternatives;
pub mod deep_pattern_nesting;
pub mod unsourced_constant;
pub mod provenance_inventory;
pub mod context_erasure;
pub mod semantic_field_loss;
pub mod decision_ownership;
